### ISSUE TITLE
Error when running Sample (without any modifications) - not found: object router

### ISSUE THREAD

**Issue by ValckeM** [mliarakos/lagom-scalajs-example#5]
Hello,

Thank you for the lagom-scalajs library. 

I'm trying to run this sample as described in the project but I'm getting 2 errors (see below).
They are related to the Play UI. Probably they are easy to fix but unfortunately I'm not familiar with Play (I use Lagom without Play as front-end). Any idea of why it wont run?

![image](https://user-images.githubusercontent.com/7032224/115845924-aab81980-a421-11eb-82c3-e49d3bfb6c38.png)

**Comment by mliarakos** [comment]
[Play Routing](https://www.playframework.com/documentation/2.8.x/ScalaRouting) classes are generated at compile time. Unfortunately, IDEs without built-in Play support often aren't aware of this and will fail on the first compile because the route classes don't exist yet. The simplest solution is to compile the project once from the command line:

```sh
cd lagom-scalajs-example
sbt compile
```

That will generate the route classes to get your IDE started. After that your IDE can handle subsequent compiles. Try that out and let me know if it solves the issue.

This is the case for me using IntelliJ IDEA Community Edition. I believe IntelliJ IDEA Ultimate doesn't have this issue because it has Play support. What IDE are you using?

**Comment by ValckeM** [comment]
Thank you, I was indeed running the commands inside the console of IntelliJ IDEA Community Edition.
Running sbt compile from command line fixed it.

Thanks a lot!
